package ar.edu.unlu.Enums;

public enum EstadoActual {
    INICIALIZAR_JUEGO,
    TURNO_JUGADOR,
    MENU_TURNO,

    ESPERANDO_TURNO,
    COLOCAR_FICHA,
    SELECCIONAR_ORIGEN_MOVER,
    SELECCIONAR_DESTINO_MOVER,
    SELECCIONAR_ORIGEN_MOVER_SUPER,
    SELECCIONAR_DESTINO_MOVER_SUPER,
    PARTIDA_SUSPENDIDA,
    PARTIDA_TERMINADA,
    SELECCIONAR_FICHA_PARA_ELIMINAR

}
